### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by SecretPocketCat** [SecretPocketCat/gallerydemo#2]
### Todo
- [x] fix mobile/small width
  - CSS (media queries)
  - init based on width ~~switch between Isotope and Flickity~~ - 2 isotope layouts
- [x] lightbox layout for mobile view
- [x] add skip option to AddPhotos (already in controller)
  - view
  - JS
- [x] add a _NewLensPartial to AddPhotos (through an AJAX request)
- [x] add extra options to FindUser
  - num of photos
  - ~~search by tags~~
- [x] photos left to add
- [x] move config data aside and setup a class for it
- [x] skipped photos view
- ~~option to skip photo in editPhoto and deletePhoto~~
- [x] option to skip/archive photo at admin/index
- ~~clean models and VMs~~
- ~~clean up/generalise site.css~~
- [x] more compact admin navbar (photos + skipped photos, add photos + find photos)
- [x] random photos order in the main/lens galleries
- [x] lenses view for home
- [x] option to hide lenses from the lens gallery (misc)
- [x] logging
- [x] admin login
- [x] custom error-messages
- [x] "no JS" warning

**Comment by SecretPocketCat** [comment]
Mobile view addressed in fe39c6cd546d6095680158a144326d49247eb867

**Comment by SecretPocketCat** [comment]
Skip option added in 7d9b56b9
A skipped-photos-view would probably come in handy (isotope container consisting of small thumbnail urls with hover options of delete and re-add

**Comment by SecretPocketCat** [comment]
lighbox and popup data for small thumbnails added in c335a4b6
